-- For HSQL
CREATE TABLE UserTest(id int, username varchar(100), PRIMARY KEY (id));
--ALTER TABLE User ALTER COLUMN id 
-- SET GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1);

-- For Mysql
-- CREATE TABLE UserTest(id int  AUTO_INCREMENT, username varchar(100), PRIMARY KEY (id));
