// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/tutorial/addressbook.proto

package org.springframework.issues.tutorial;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_PhoneNumber_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_PhoneNumber_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBook_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/proto/tutorial/addressbook.pr" +
      "oto\"\310\001\n\006Person\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005" +
      "\022\r\n\005email\030\003 \001(\t\022\"\n\005phone\030\004 \003(\0132\023.Person." +
      "PhoneNumber\032D\n\013PhoneNumber\022\016\n\006number\030\001 \002" +
      "(\t\022%\n\004type\030\002 \001(\0162\021.Person.PhoneType:\004HOM" +
      "E\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004" +
      "WORK\020\002\"&\n\013AddressBook\022\027\n\006person\030\001 \003(\0132\007." +
      "PersonB:\n#org.springframework.issues.tut" +
      "orialB\021AddressBookProtosP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "Phone", });
          internal_static_Person_PhoneNumber_descriptor =
            internal_static_Person_descriptor.getNestedTypes().get(0);
          internal_static_Person_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_PhoneNumber_descriptor,
              new java.lang.String[] { "Number", "Type", });
          internal_static_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddressBook_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
