// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/tutorial/addressbook.proto

package org.springframework.issues.tutorial;

public interface AddressBookOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .Person person = 1;
  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<org.springframework.issues.tutorial.Person> 
      getPersonList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  org.springframework.issues.tutorial.Person getPerson(int index);
  /**
   * <code>repeated .Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<? extends org.springframework.issues.tutorial.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  org.springframework.issues.tutorial.PersonOrBuilder getPersonOrBuilder(
      int index);
}
