// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/tutorial/addressbook.proto

package org.springframework.issues.tutorial;

public interface PersonOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string name = 1;
  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // required int32 id = 2;
  /**
   * <code>required int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 2;</code>
   */
  int getId();

  // optional string email = 3;
  /**
   * <code>optional string email = 3;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  // repeated .Person.PhoneNumber phone = 4;
  /**
   * <code>repeated .Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<org.springframework.issues.tutorial.Person.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .Person.PhoneNumber phone = 4;</code>
   */
  org.springframework.issues.tutorial.Person.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .Person.PhoneNumber phone = 4;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<? extends org.springframework.issues.tutorial.Person.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .Person.PhoneNumber phone = 4;</code>
   */
  org.springframework.issues.tutorial.Person.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
